name: DoubleJump
main: MulkiAqi192\DoubleJump\Main
author: MulkiAqi192
api: 4.0.0
version: 1.0

commands:
 djump:
  description: "Jump straight twice to the sky with double jump mode"
  permission: djump.cmd

permissions:
  djump.cmd:
    description: "A permission to use djump command"
    default: op